#!/bin/bash

if [ "$(pgrep -f "$0" -c)" -gt 1 ]; then
	echo "already running: $0"
	exit 0
fi

function set_usb_sound {
	local pid user userid sink
	pid=$(pgrep pulseaudio)
	user=$(strings "/proc/$pid/environ" | grep USER= | sed 's/.*=//')
	userid=$(id -u "$user")

	sleep 5

	sink='alsa_output.usb-C-Media_Electronics_Inc.'
	sink+='_USB_Advanced_Audio_Device-00.analog-stereo'

	source='alsa_input.usb-C-Media_Electronics_Inc.'
	source+='_USB_Advanced_Audio_Device-00.mono-fallback'

	sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
		sh -c "pactl set-default-sink $sink"

	sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
		sh -c "pactl set-default-source $source"

	#sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
	#	sh -c "pactl set-source-mute $source 1"

	module_loopback=$(
		sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
			sh -c "pactl list short modules | grep 'module-loopback.*source=${source}'"
	)

	if [ -z "$module_loopback" ]; then
		sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
			sh -c "pactl load-module module-loopback latency_msec=1 source=${source}"
	fi
}

set_usb_sound &
