#!/bin/bash

if [ "$(pgrep -f "$0" -c)" -gt 1 ]; then
	echo "already running: $0"
	exit 0
fi

function set_usb_mic_webcam {
	local pid user userid modules source
	pid=$(pgrep pulseaudio)
	user=$(strings "/proc/$pid/environ" | grep USER= | sed 's/.*=//')
	userid=$(id -u "$user")

	sleep 5
	modules=$(
		sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
			sh -c "pactl list modules | grep 'Name: module-loopback'"
	)
	source='alsa_input.usb-046d_HD_Pro_Webcam_C920_A797B9AF-02.analog-stereo'

	if [ -n "$modules" ]; then
		sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
			sh -c "pactl load-module module-loopback latency_msec=1 $source"
	fi

	sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
		sh -c "pactl set-default-source $source"

	sudo -u "$user" env XDG_RUNTIME_DIR="/run/user/$userid" \
		sh -c "pactl set-source-mute $source 1"

}

set_usb_mic_webcam &
