#!/bin/bash

if ! command -v lastversion &> /dev/null; then
	echo "This program require 'lastversion', you can install it with:"
	echo "pip3 install --user lastversion"
	exit 1
fi

function gitchk {
	declare -A GIT_PACKAGE_TO_CHECK
	declare -A GIT_PACKAGE_TO_IGNORE
	declare -A GIT_PACKAGE_VERSION

	# shellcheck disable=SC1090
	source "$HOME/.gitchkrc"

	local latest_version current_version
	local chk version
	local git_url='https://github.com'

	declare -i git_to_update=0
	echo "Checking latest versions from ${git_url}"
	for p in "${!GIT_PACKAGE_TO_CHECK[@]}"; do
		current_version="${GIT_PACKAGE_VERSION[$p]}"
		latest_version=$(
			lastversion "${git_url}/${GIT_PACKAGE_TO_CHECK[$p]}"
		)
		if [ "$latest_version" = "${GIT_PACKAGE_TO_IGNORE[$p]}" ]; then
			chk="[$(tput setaf 3)✔$(tput sgr0)]"
			version="$current_version (ignored: $latest_version)"
		elif [ "$current_version" != "$latest_version" ]; then
			chk="[$(tput setaf 1)✘$(tput sgr0)]"
			version="$current_version (latest: $latest_version)"
			git_to_update+=1
		else
			chk="[$(tput setaf 3)✔$(tput sgr0)]"
			version="$current_version"
		fi
		printf "%s %-20s %s\n" "$chk" "$p" "$version"
	done

	echo "$git_to_update" > "$HOME/.gitchk_count"

}

gitchk
