#!/bin/bash

GIT_PACKAGE_TO_CHECK=(
	['fzf']='junegunn/fzf'
	['shellcheck']='koalaman/shellcheck'
	['ctags']='universal-ctags/ctags'
	['docopts']='docopt/docopts'
	['cheat']='cheat/cheat'
	['semantic-release']='go-semantic-release/semantic-release'
)

GIT_PACKAGE_VERSION=(
	['fzf']=$(fzf --version 2>/dev/null | awk '{print $1}')
	['shellcheck']=$(shellcheck --version 2>/dev/null| grep version: | awk '{print $2}')
	['ctags']=$(ctags --version 2>/dev/null| grep -P -o '(?<=\(p)[^)]+(?=\),)')
	['docopts']=$(docopts --version 2>/dev/null| awk '{ sub(/v/,"",$2); sub(/-/,"",$2); print $2; exit }')
	['cheat']=$(cheat --version 2>/dev/null)
	['semantic-release']=$(semantic-release --version 2>/dev/null| awk '{print $3}')
)

GIT_PACKAGE_TO_IGNORE=(
)
