#!/bin/bash

function pipchk {
	declare -a PIP_PACKAGE_TO_CHECK
	declare -A PIP_PACKAGE_TO_IGNORE

	# shellcheck disable=SC1090
	source "$HOME/.pipchkrc"

	local latest_version current_version
	local chk version
	local pypi_url='https://pypi.org/project'

	declare -i pip_to_update=0
	echo "Checking latest versions from ${pypi_url}"
	for p in "${PIP_PACKAGE_TO_CHECK[@]}"; do
		current_version=$(pip3 show "$p" | grep Version | awk '{print $2}')
		latest_version=$(
			curl -s "${pypi_url}/${p}/" |
				sed -n -e '/release__version/{n;p;q}' |
				grep -o '\S*'
		)

		if [ "$latest_version" = "${PIP_PACKAGE_TO_IGNORE[$p]}" ]; then
			chk="[$(tput setaf 2)✔$(tput sgr0)]"
			version="$current_version (ignored: $latest_version)"
		elif [ "$current_version" != "$latest_version" ]; then
			chk="[$(tput setaf 1)✘$(tput sgr0)]"
			version="$current_version (latest: $latest_version)"
			pip_to_update+=1
		else
			chk="[$(tput setaf 2)✔$(tput sgr0)]"
			version="$current_version"
		fi
		printf "%s %-20s %s\n" "$chk" "$p" "$version"
	done

	echo "$pip_to_update" > "$HOME/.pipchk_count"

}

pipchk
