#!/bin/bash
PIP_PACKAGE_TO_CHECK=(
	'bashate'
	'ansible-lint'
	'gitlint'
	'pre-commit'
	'proselint'
	'yamllint'
	'lastversion'
	'nodeenv'
	'flake8'
	'black'
)

PIP_PACKAGE_TO_IGNORE=(
	['ansible-lint']='5.0.5a1'
)
