#!/bin/bash
################################################################################
# TMUX
TMUX_HOSTS+=(
  'cpl1-infr-sec2'
)

################################################################################
# SSH-AGENT
AGENT_HOSTS+=(
  'cpl1-infr-sec2'
  'cpl1-infr-aut3'
)

################################################################################
# SDC

if [ -f /data/rootscripts/sdc ]; then
	# shellcheck disable=SC1090
  source ~/git/sdc-bash-completion/sdc.sh

  alias sdc='sudo -u asuser -i /data/rootscripts/sdc'
  alias dns='sudo su - asuser -c /data/apps/s01/prod/gestiondns/current/scripts/sync.pl'
  alias sdc-sec='sudo -u asuser -i /data/rootscripts/sdc-sec'

  #donner accès à un nouveau développeur
  function sdc-sec-newguy {
    local SDC_SEC='sudo -u asuser -i /data/rootscripts/sdc-sec'
    "$SDC_SEC" user add "$1"
    "$SDC_SEC" group useradd global_permissions "$1"
    getent passwd  "$1"
    "$SDC_SEC" user permlist "$1"
  }
fi

################################################################################
# ALIASES

alias aut3="ssh cpl1-infr-aut3"
alias mgnt="ssh cpl1-web-mgnt"

if [ -e /usr/bin/ansible ]; then
  alias ansible='sudo -u auto-it ansible'
  alias ansible-playbook='sudo -u auto-it ansible-playbook'
fi

################################################################################
# HOSTNAME_COLOR
# Test if the servername has a "P" for PROD
if [[ "${HOSTNAME%%.*}" =~ ^[a-zA-Z0-9]{4}-[^-]+-[^-]+$ ]]; then
  if [ "${HOSTNAME:1:1}" = 'p' ]; then
    export ICON_COLOR="\033[01;31m"
  fi
fi

# vim: ff=sh ts=2 sw=2
