#!/bin/bash

################################################################################
# UPDATES
PIPCHK_HOSTS+=(
	'odin'
)
GITCHK_HOSTS+=(
	'odin'
)

################################################################################
# SSH-AGENT
AGENT_HOSTS+=(
	'odin'
)

################################################################################
# HOSTNAME_COLOR

case "$HOSTNAME" in
	"odin")
		HOSTNAME_COLOR="\033[01;36m"
		;;
esac

export HOSTNAME_COLOR
