#!/bin/bash
################################################################################
# TMUX
TMUX_HOSTS+=(
	'linux-patrick'
)

################################################################################
# UPDATES
PIPCHK_HOSTS+=(
	'teluq-100251'
	'linux-patrick'
)
GITCHK_HOSTS+=(
	'teluq-100251'
	'linux-patrick'
)

################################################################################
# SSH-AGENT
AGENT_HOSTS+=(
	'teluq-100251'
	'linux-patrick'
)

################################################################################
# SSH_TUN
SSH_TUN_LIST+=(
	'1:patrick@132.214.19.24:8888'
)

################################################################################
# HOSTNAME_COLOR

case "${HOSTNAME%%.*}" in
	"teluq-100251")
		HOSTNAME_COLOR="\033[01;36m"
		;;
	'linux-patrick')
		HOSTNAME_COLOR="\033[01;31m"
		;;
esac

PROMPTBOX_COLOR="\033[0;35m"

################################################################################
# PROXY HTTP
case "${HOSTNAME%%.*}" in
	'linux-patrick')
		http_proxy='http://nenuphare2.teluq.uquebec.ca:3128'
		https_proxy='http://nenuphare2.teluq.uquebec.ca:3128'
		ftp_proxy='http://nenuphare2.teluq.uquebec.ca:3128'
		;;
esac

export HOSTNAME_COLOR PROMPTBOX_COLOR SSH_TUN_LIST
export http_proxy https_proxy ftp_proxy
