#!/bin/bash

################################################################################
# UPDATES
PIPCHK_HOSTS+=(
	'odin'
	'linux-patrick'
)
GITCHK_HOSTS+=(
	'odin'
	'linux-patrick'
)

################################################################################
# SSH-AGENT
AGENT_HOSTS+=(
	'odin'
	'linux-patrick'
)

################################################################################
# SSH_TUN
SSH_TUN_LIST+=(
	'1:patrick@132.214.19.24:8888'
)



################################################################################
# HOSTNAME_COLOR

case "$HOSTNAME" in
	"odin")
		HOSTNAME_COLOR="\033[01;36m"
		;;
	'linux-patrick')
		HOSTNAME_COLOR="\033[01;31m"
		;;
esac

PROMPTBOX_COLOR="\033[0;35m"

export HOSTNAME_COLOR PROMPTBOX_COLOR SSH_TUN_LIST
